modLoader="javafml"
loaderVersion="[11,)"
license="MIT"

[[mods]]
modId="simpletpa"
version="${version}"
displayName="SimpleTPA"
description="Adds player-to-player teleport requests, approvals, and persistent auto-accept lists."
authors="brainage04"

[[dependencies.simpletpa]]
modId="neoforge"
type="required"
versionRange="[${neoforge_version},)"
ordering="NONE"
side="BOTH"

[[dependencies.simpletpa]]
modId="minecraft"
type="required"
versionRange="[${minecraft_version},)"
ordering="NONE"
side="BOTH"

[[dependencies.simpletpa]]
modId="brainagelib"
type="required"
versionRange="[${brainagelib_version},)"
ordering="NONE"
side="BOTH"
